### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by rakkar1974** [EnoxSoftware/AVProWithOpenCVForUnityExample#2]
Following these steps:
Download the latest release unitypackage. [AVProWithOpenCVForUnityExample.unitypackage](https://github.com/EnoxSoftware/AVProWithOpenCVForUnityExample/releases)
Create New Project. (AVProWithOpenCVForUnityExample)
Import OpenCVForUnity from AssetStore
Import UnityPlugin-AVProVideo-Latest-Trial.unitypackage
Import UnityPlugin-AVProLiveCamera-Latest-Trial.unitypackage
Import AVProWithOpenCVForUnityExample.unitypackage
Add the "Assets/AVProWithOpenCVForUnityExample/*.unity" files to the "Scenes In Build" list in the "Build Settings" window.
Build and Deploy.

The files you specify don't come up on search engine searches and you didn't provide a link. However, I attemped to use the latest I could find:
AVProWithOpenCVForUnityExample_v1.0.3.unitypackage
UnityPlugin-AVProVideo-v3.2.7-Trial.unitypackage
UnityPlugin-AVProLiveCamera-v2.9.3-Trial.unitypackage

Doing so, I get 14 errors attemping to compile with Unity 60001.6f1. The first is:
Assets\AVProWithOpenCVForUnityExample\AVProLiveCameraAsyncGPUReadback2MatHelperExample\AVProLiveCameraAsyncGPUReadback2MatHelperExample.cs(6,22): error CS0234: The type or namespace name 'UnityIntegration' does not exist in the namespace 'OpenCVForUnity' (are you missing an assembly reference?)

**Comment by EnoxSoftware** [comment]
Thank you for your inquiry.
AVProWithOpenCVForUnityExample_v1.0.3.unitypackage is compatible with OpenCVForUnity 3.0.0 or later, so please import version 3.0.0 or later.

OpenCVForUnity v3.0.0
AVProWithOpenCVForUnityExample_v1.0.3.unitypackage
UnityPlugin-AVProVideo-v3.2.7-Trial.unitypackage
UnityPlugin-AVProLiveCamera-v2.9.3-Trial.unitypackage

**Comment by rakkar1974** [comment]
Thank you, I am now able to compile. AVProLiveCameraAsyncGPUReadback2MatHelperExample has no output to the screen, however this is most likely caused by https://github.com/RenderHeads/UnityPlugin-AVProLiveCamera/issues/58 . Assuming that is the case, I believe this ticket can be closed.

**Comment by EnoxSoftware** [comment]
In Unity 6000.1.10f1 Universal 3D, we confirmed that AVProLiveCamera's GUIDemo did not display the camera image, and AVProLiveCameraAsyncGPUReadback2MatHelperExample also did not display the camera image.
It works fine with Unity 2021.3.35f1 Built-in, so it may be a bug in AVProLiveCamera.
